#!/usr/bin/env python3
"""
gen_app_strings.py — export the firmware EN/IT string table to the Flutter app
==============================================================================
Single source of truth for UI wording: main/lang.c (generated by gen_lang.py).
This script reads that table and writes a Dart class so the companion app uses
exactly the same terms as the display (Scan/Cerca, Connect/Connetti, ...).

    python3 scripts/gen_app_strings.py ../FilMachine_App/lib/l10n/fm_strings.dart

Rules applied on the way to Dart:
  * key = macro name without the trailing `_text` (`wifiScan_text` → `wifiScan`,
    `languageList` stays `languageList`);
  * the display fonts only cover 0x20-0x7F, so Italian is written with a
    trailing apostrophe ("Complessita'"); the phone has real fonts, so those
    become proper accented vowels ("Complessità"). Words that take an acute
    accent are listed in ACUTE below;
  * printf placeholders (%d %u %lu %s %.1f ...) are kept verbatim; the app
    formats them with FmStrings.fmt();
  * `\n` stays a newline.

Re-run this whenever lang.c changes, then commit the Dart file in the app repo.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LANG_C = os.path.join(ROOT, "main/lang.c")

# Italian words ending in a stressed -e that take an acute accent (é). Everything
# else written as e' becomes è (the common case: è, caffè, cioè, ...).
ACUTE = {"perche", "poiche", "affinche", "benche", "finche", "giacche",
         "nonche", "purche", "sicche", "ne", "se", "ventitre", "trentatre"}

ENTRY = re.compile(
    r'\[STR_(\w+)\]\s*=\s*\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*(?:"((?:[^"\\]|\\.)*)"|NULL)\s*\}')


def c_unescape(s: str) -> str:
    return (s.replace('\\n', '\n').replace('\\t', '\t')
             .replace('\\"', '"').replace('\\\\', '\\'))


def accentify(s: str) -> str:
    """Turn the display's ASCII apostrophe convention into real accents."""
    def repl(m):
        word, vowel = m.group(1), m.group(2)
        upper = vowel.isupper()
        v = vowel.lower()
        if v == 'e':
            acc = 'é' if word.lower() + 'e' in ACUTE else 'è'
        else:
            acc = {'a': 'à', 'i': 'ì', 'o': 'ò', 'u': 'ù'}[v]
        if upper:
            acc = acc.upper()
        return word + acc
    # vowel + apostrophe at the end of a word (followed by space/punct/end)
    return re.sub(r"([A-Za-z]*)([aeiouAEIOU])'(?=$|[\s.,;:!?)\n])", repl, s)


def dart_str(s: str) -> str:
    return ("'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$')
            .replace('\n', '\\n') + "'")


def key_of(name: str) -> str:
    return name[:-5] if name.endswith('_text') else name


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "fm_strings.dart")
    src = open(LANG_C, encoding='utf-8').read()
    entries = []
    for m in ENTRY.finditer(src):
        name, en, it = m.group(1), c_unescape(m.group(2)), m.group(3)
        it = accentify(c_unescape(it)) if it is not None else en
        entries.append((key_of(name), en, it))
    if not entries:
        sys.exit("no entries parsed from " + LANG_C)

    lines = [
        "// GENERATED FILE — do not edit by hand.",
        "// Source: FilMachine_Reworked/main/lang.c via scripts/gen_app_strings.py",
        "// The app and the machine display share this table so wording is identical.",
        "",
        "/// Firmware UI strings, EN (lang 0) / IT (lang 1).",
        "class FmStrings {",
        "  /// 0 = English, 1 = Italiano (same codes as the firmware `language` setting).",
        "  final int lang;",
        "  const FmStrings(this.lang);",
        "",
        "  String _t(String en, String it) => lang == 1 ? it : en;",
        "",
        "  /// Format a printf-style firmware string (%d, %u, %lu, %s, %.1f, %%).",
        "  static String fmt(String pattern, List<Object?> args) {",
        "    var i = 0;",
        "    return pattern.replaceAllMapped(",
        "        RegExp(r'%(%|\\.?\\d*(?:l|ll|h)?[dusfiux])'), (m) {",
        "      if (m.group(1) == '%') return '%';",
        "      final spec = m.group(1)!;",
        "      final a = i < args.length ? args[i++] : '';",
        "      final prec = RegExp(r'\\.(\\d+)f').firstMatch(spec);",
        "      if (prec != null && a is num) {",
        "        return a.toStringAsFixed(int.parse(prec.group(1)!));",
        "      }",
        "      if (spec.endsWith('f') && a is num) return a.toStringAsFixed(2);",
        "      return '$a';",
        "    });",
        "  }",
        "",
    ]
    seen = set()
    for key, en, it in entries:
        if key in seen:
            continue
        seen.add(key)
        if en == it:
            lines.append(f"  String get {key} => {dart_str(en)};")
        else:
            lines.append(f"  String get {key} => _t({dart_str(en)}, {dart_str(it)});")
    lines += ["}", ""]
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    open(out, 'w', encoding='utf-8').write("\n".join(lines))
    print(f"{len(seen)} strings → {out}")


if __name__ == "__main__":
    main()
